on:
  workflow_dispatch:
    inputs:
      redmine_url:
        type: string
        description: 'URL to Redmine instance'
        required: true
      redmine_api_key:
        type: string
        description: 'Redmine API token (from My account)'
        required: true
      redmine_project_id:
        type: string
        description: 'Redmine project ID'
        required: true
      redmine_parent_issue_id:
        type: string
        description: 'Parent contract (optional)'
        required: false

name: 'Create project skeleton'
jobs:
  prepare:
    name: 'Create new project structure'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 'Install dependencies'
        run: >
          composer install -q --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader

      - name: 'Export Redmine API key to environment'
        run: >
          echo $(jq -r '.inputs.redmine_api_key' ${GITHUB_EVENT_PATH}) > redmine.key

      - name: 'Create project issues'
        run: >
          ./vendor/bin/robo redmine:create-new-project ${{ inputs.redmine_url }} ${{ inputs.redmine_project_id }} ${{ inputs.redmine_parent_issue_id }}
